DROP TYPE IF EXISTS states;
CREATE TYPE states AS ENUM ('open', 'canceled', 'executed');

CREATE TABLE ACCOUNT(
    ACCOUNT_ID INT PRIMARY KEY,
    BALANCE DECIMAL(12,2),
    VERSION integer NOT NULL DEFAULT 1
);

CREATE TABLE SYMBOL(
    ACCOUNT_ID INT,
    SYM VARCHAR(256),
    AMOUNT INT,
    VERSION integer NOT NULL DEFAULT 1,
    CONSTRAINT symbol_pk PRIMARY KEY (ACCOUNT_ID, SYM),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ORDERS(
    TRANS_ID SERIAL,
    ACCOUNT_ID INT,
    SYM VARCHAR(256),
    AMOUNT INT,
    LIMIT_PRICE DECIMAL(20,2),
    STATE states,
    TIME TIMESTAMP,
    VERSION integer NOT NULL DEFAULT 1,
    CONSTRAINT order_pk PRIMARY KEY (TRANS_ID, TIME)
);