CREATE TYPE states AS ENUM ('open', 'canceled', 'executed');

CREATE TABLE ACCOUNT(
    ACCOUNT_ID INT PRIMARY KEY,
    BALANCE DECIMAL(12,2)
);

CREATE TABLE SYMBOL(
    SYM_ID SERIAL PRIMARY KEY,
    ACCOUNT_ID INT,
    SYM VARCHAR(256),
    AMOUNT INT,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ORDERS(
    ORDER_ID SERIAL PRIMARY KEY,
    ACCOUNT_ID INT,
    SYM VARCHAR(256),
    AMOUNT INT,
    LIMIT_PRICE DECIMAL(20,2),
    STATE states,
    TIME TIMESTAMP
);